from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any

class MatchedSchemeCard(BaseModel):
    name: str = Field(..., description="Official scheme name")
    short_description: str = Field(..., description="One or two sentence simple summary")
    reason: Optional[str] = Field(None, description="Why this scheme may be relevant to user")
    eligibility: Optional[str] = Field(None, description="Key eligibility conditions")
    benefits: Optional[str] = Field(None, description="Coverage or financial benefits")
    documents: Optional[List[str]] = Field(default_factory=list, description="Required documents")

class SourceReference(BaseModel):
    document: str = Field(..., description="Source document file name")
    page: int = Field(..., description="Page number where content was found")
    score: Optional[float] = Field(None, description="Relevance score of retrieved chunk")
    snippet: Optional[str] = Field(None, description="Short snippet from retrieved chunk")

class ChatRequest(BaseModel):
    message: str = Field(..., min_length=1, description="User question or input message")
    language: str = Field("en", description="Language code (en, hi, ta, te, kn, ml, mr, bn, gu)")
    conversation_id: Optional[str] = Field(None, description="Optional persistent conversation ID")
    temp_document_id: Optional[str] = Field(None, description="Optional temporary document session ID")

class ChatResponse(BaseModel):
    answer: str = Field(..., description="Short introductory grounded answer generated by MITRA AI")
    voice_answer: Optional[str] = Field(None, description="Ultra-short concise text for TTS voice playback")
    matched_schemes: List[MatchedSchemeCard] = Field(default_factory=list, description="Structured scheme cards")
    needs_more_information: List[str] = Field(default_factory=list, description="Missing fields needed for complete verification")
    language: str = Field(..., description="Resolved language code")
    sources: List[SourceReference] = Field(default_factory=list, description="Retrieved source document references")
    conversation_id: str = Field(..., description="Active conversation session ID")
    intent: str = Field(..., description="Classified intent (health_scheme, greeting, medical_safety, follow_up, out_of_scope)")
    disclaimer: str = Field(..., description="Safety and official eligibility disclaimer")
