/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#322032",
        "on-primary": "#ffffff",
        "primary-container": "#493548",
        "on-primary-container": "#b89eb5",
        "primary-fixed": "#f7daf2",
        "primary-fixed-dim": "#dabed6",
        "on-primary-fixed": "#271527",
        "on-primary-fixed-variant": "#554054",
        "inverse-primary": "#dabed6",
        "secondary": "#934a36",
        "on-secondary": "#ffffff",
        "secondary-container": "#fea188",
        "on-secondary-container": "#783523",
        "secondary-fixed": "#ffdbd1",
        "secondary-fixed-dim": "#ffb5a1",
        "on-secondary-fixed": "#3b0800",
        "on-secondary-fixed-variant": "#753321",
        "tertiary": "#352200",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#513600",
        "on-tertiary-container": "#cf9d45",
        "tertiary-fixed": "#ffdeac",
        "tertiary-fixed-dim": "#f4be62",
        "on-tertiary-fixed": "#281900",
        "on-tertiary-fixed-variant": "#604100",
        "surface": "#faf8fe",
        "surface-dim": "#dbd9df",
        "surface-bright": "#faf8fe",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f8",
        "surface-container": "#efedf3",
        "surface-container-high": "#e9e7ed",
        "surface-container-highest": "#e3e2e7",
        "on-surface": "#1b1b1f",
        "on-surface-variant": "#4c454a",
        "inverse-surface": "#2f3035",
        "inverse-on-surface": "#f2f0f6",
        "outline": "#7d747b",
        "outline-variant": "#cfc3ca",
        "surface-tint": "#6e576c",
        "surface-sand": "#F7F1E8",
        "surface-warm-white": "#FFFCF7",
        "text-charcoal": "#292A2D",
        "text-slate": "#65656A",
        "border-warm-gray": "#DED6CB",
        "status-success": "#397052",
        "status-warning": "#9A6B24",
        "status-error": "#A94D45",
        "background": "#faf8fe",
        "on-background": "#1b1b1f",
        "surface-variant": "#e3e2e7",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        gutter: "1rem",
        "gutter-tablet": "1.5rem",
        "gutter-desktop": "2rem",
        margin: "1rem",
        "margin-tablet": "2rem",
        "margin-desktop": "3rem",
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem"
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-sm": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "display-lg": ["40px", { lineHeight: "48px", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-sm": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-lg": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
